### ISSUE TITLE
[Beta V2 Feedback] Collate 

### ISSUE THREAD

**Issue by abaz-oceans** [cbirdferrer/collatrix#20]
## System Information 

System: Windows
OS: nt
Python Version: 3.10.12
Python Implementation: CPython
Release: 10
Version: 10.0.19045
Machine: AMD64
Processor: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
Current Working DirectoryC:\Windows\system32
CollatriX version: 2.0 beta

## Verify that you can carry out the following actions

Mark inside the brackets with an [x] to 

- [ ] Wrangle LiDAR ([ ] GPX or [ ] Fightware csv)
- [ ] Pull LiDAR for Videos
- [ ] Merge LiDAR for Videos
- [ ] Pull/Merge LiDAR for Images
- [X ] Collate MorphoMetriX version 2 outputs
- [ ] Calculate body condition metrics (list which metrics here: ____)

## If you encounter an error, please copy attach the crash log text file, any inputs you were trying to use, and any screenshots that might be helpful.

Traceback (most recent call last):
  File "collatrix\__main__.py", line 1590, in collate
  File "ntpath.py", line 211, in split
TypeError: expected str, bytes or os.PathLike object, not float

## Please provide additional feedback and/or suggestions below

Hi Clara, 

Is there a maximum number of files that CollatriX can collate at a time within a folder? I was able to collate all of my smaller folders (max. of 48 files per folder) of MorphoMetriX V2 outputs, but kept receiving this crash log for 2 of my larger files (exceeding 50+ files per folder). Once I saved the crash log, it still says "...running..." underneath the run button.

Thank you

**Comment by abaz-oceans** [comment]
Hello Clara, 

Turns out the problem wasn't a file size issue. I went back and checked all of my output spreadsheets for small errors (e.g., image path missing, typos like TL written as tl, and duplicate measurements). Correcting them did the trick!

Sorry for any inconvenience, I was hoping this issue was something minor that I missed! Thank you.
